// Package tokenizer is... TODO THIS

package tokenizer

const (
	RULENAME_KEYWORD             = "KEYWORD"
	RULENAME_SYMBOL              = "SYMBOL"
	RULENAME_OTHER               = "OTHER"
	SYMBOLIC_NAME_NON_KEYWORD    = "IDENTIFIER"
	SYMBOLIC_NAME_WHITESPACE     = "WHITESPACE"
	SYMBOLIC_NAME_NEWLINE        = "NEWLINE"
	SYMBOLIC_NAME_UNKNOWN_SYMBOL = "UNKNOWN"
	SYMBOLIC_NAME_COMMENT        = "COMMENT"
	SYMBOLIC_NAME_STRING         = "STRING"
)
